POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZW1haWwuY29tIiwiZXhwIjoxNzEwNzA3MDI4LCJ1c2VySUQiOjF9.UXuleN5JkO1mYvNgTKA6rYrPYQVsOnTl63lKkR_fass

{
    "Name": "123",
    "Description": "123",
    "Location": "123",
    "Date": "2024-01-01T15:30:00.000Z"
}