DELETE http://localhost:8080/events/3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGVtYWlsLmNvbSIsImV4cCI6MTcxMDcwNDM0MywidXNlcklEIjoyfQ.ZzrGJJVkUepm0cyvXmryKlQRZ0OaMQAdarFkPH-itxA