PUT http://localhost:8080/events/2
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGVtYWlsLmNvbSIsImV4cCI6MTcxMDcwNDM0MywidXNlcklEIjoyfQ.ZzrGJJVkUepm0cyvXmryKlQRZ0OaMQAdarFkPH-itxA

{
    "name": "updated name",
    "location": "location 4",
    "date": "2024-01-01T15:30:00.000Z"
}